package com.namarahul.namarahulcollab.objectarrayreturntype;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Response DTO for transferring employee data.
 * Contains basic personal information of an employee.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OJuniorEmployeeResponse {

    /**
     * Unique identifier for the employee.
     * This is typically auto-generated by the database.
     */
    private String firstName;

    /**
     * Last name of the employee.
     * Contains the employee's family name or surname.
     */
    private String lastName;
}
