spring:
  application:
    name: namarahulcollab
  datasource:
    url: jdbc:mysql://localhost:3306/empdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '02560256'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /
  api-docs:
    enabled: true