package com.namarahul.namarahulcollab.dto.Request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * DTO for transferring employee data in API requests.
 * Contains basic personal and contact information of an employee.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SaveEmployeeRequest {

    /**
     * Unique identifier for the employee.
     * This is typically auto-generated by the database.
     */
    private Integer id;

    /**
     * First name of the employee.
     * Contains the employee's given name.
     */
    private String firstName;

    /**
     * Last name of the employee.
     * Contains the employee's family name or surname.
     */
    private String lastName;

    /**
     * Email address of the employee.
     * Used for communication and as a unique identifier in the system.
     */
    private String email;

    /**
     * Phone number of the employee.
     * Used for contact purposes and communication.
     */
    private String phoneNumber;

    /**
     * Job title or position of the employee in the organization.
     * Describes the role or position held by the employee.
     */
    private String jobTitle;

    /**
     * Salary of the employee.
     * Represents the employee's compensation amount.
     */
    private BigDecimal salary;

    /**
     * Indicates if the employee is currently active in the system.
     * True if the employee is active, false if inactive or terminated.
     */
    private Boolean isActive;
}
